INSERT INTO country (id, name, iso2) VALUES (1, 'Afghanistan', 'AF');
INSERT INTO country (id, name, iso2) VALUES (2, 'Aland Islands', 'AX');
INSERT INTO country (id, name, iso2) VALUES (3, 'Albania', 'AL');
INSERT INTO country (id, name, iso2) VALUES (4, 'Algeria', 'DZ');
INSERT INTO country (id, name, iso2) VALUES (5, 'American Samoa', 'AS');
INSERT INTO country (id, name, iso2) VALUES (6, 'Andorra', 'AD');
INSERT INTO country (id, name, iso2) VALUES (7, 'Angola', 'AO');
INSERT INTO country (id, name, iso2) VALUES (8, 'Anguilla', 'AI');
INSERT INTO country (id, name, iso2) VALUES (9, 'Antarctica', 'AQ');
INSERT INTO country (id, name, iso2) VALUES (10, 'Antigua And Barbuda', 'AG');
INSERT INTO country (id, name, iso2) VALUES (11, 'Argentina', 'AR');
INSERT INTO country (id, name, iso2) VALUES (12, 'Armenia', 'AM');
INSERT INTO country (id, name, iso2) VALUES (13, 'Aruba', 'AW');
INSERT INTO country (id, name, iso2) VALUES (14, 'Australia', 'AU');
INSERT INTO country (id, name, iso2) VALUES (15, 'Austria', 'AT');
INSERT INTO country (id, name, iso2) VALUES (16, 'Azerbaijan', 'AZ');
INSERT INTO country (id, name, iso2) VALUES (17, 'The Bahamas', 'BS');
INSERT INTO country (id, name, iso2) VALUES (18, 'Bahrain', 'BH');
INSERT INTO country (id, name, iso2) VALUES (19, 'Bangladesh', 'BD');
INSERT INTO country (id, name, iso2) VALUES (20, 'Barbados', 'BB');
INSERT INTO country (id, name, iso2) VALUES (21, 'Belarus', 'BY');
INSERT INTO country (id, name, iso2) VALUES (22, 'Belgium', 'BE');
INSERT INTO country (id, name, iso2) VALUES (23, 'Belize', 'BZ');
INSERT INTO country (id, name, iso2) VALUES (24, 'Benin', 'BJ');
INSERT INTO country (id, name, iso2) VALUES (25, 'Bermuda', 'BM');
INSERT INTO country (id, name, iso2) VALUES (26, 'Bhutan', 'BT');
INSERT INTO country (id, name, iso2) VALUES (27, 'Bolivia', 'BO');
INSERT INTO country (id, name, iso2) VALUES (28, 'Bosnia and Herzegovina', 'BA');
INSERT INTO country (id, name, iso2) VALUES (29, 'Botswana', 'BW');
INSERT INTO country (id, name, iso2) VALUES (30, 'Bouvet Island', 'BV');
INSERT INTO country (id, name, iso2) VALUES (31, 'Brazil', 'BR');
INSERT INTO country (id, name, iso2) VALUES (32, 'British Indian Ocean Territory', 'IO');
INSERT INTO country (id, name, iso2) VALUES (33, 'Brunei', 'BN');
INSERT INTO country (id, name, iso2) VALUES (34, 'Bulgaria', 'BG');
INSERT INTO country (id, name, iso2) VALUES (35, 'Burkina Faso', 'BF');
INSERT INTO country (id, name, iso2) VALUES (36, 'Burundi', 'BI');
INSERT INTO country (id, name, iso2) VALUES (37, 'Cambodia', 'KH');
INSERT INTO country (id, name, iso2) VALUES (38, 'Cameroon', 'CM');
INSERT INTO country (id, name, iso2) VALUES (39, 'Canada', 'CA');
INSERT INTO country (id, name, iso2) VALUES (40, 'Cape Verde', 'CV');
INSERT INTO country (id, name, iso2) VALUES (41, 'Cayman Islands', 'KY');
INSERT INTO country (id, name, iso2) VALUES (42, 'Central African Republic', 'CF');
INSERT INTO country (id, name, iso2) VALUES (43, 'Chad', 'TD');
INSERT INTO country (id, name, iso2) VALUES (44, 'Chile', 'CL');
INSERT INTO country (id, name, iso2) VALUES (45, 'China', 'CN');
INSERT INTO country (id, name, iso2) VALUES (46, 'Christmas Island', 'CX');
INSERT INTO country (id, name, iso2) VALUES (47, 'Cocos (Keeling) Islands', 'CC');
INSERT INTO country (id, name, iso2) VALUES (48, 'Colombia', 'CO');
INSERT INTO country (id, name, iso2) VALUES (49, 'Comoros', 'KM');
INSERT INTO country (id, name, iso2) VALUES (50, 'Congo', 'CG');
INSERT INTO country (id, name, iso2) VALUES (51, 'Democratic Republic of the Congo', 'CD');
INSERT INTO country (id, name, iso2) VALUES (52, 'Cook Islands', 'CK');
INSERT INTO country (id, name, iso2) VALUES (53, 'Costa Rica', 'CR');
INSERT INTO country (id, name, iso2) VALUES (54, 'Cote D Ivoire (Ivory Coast)', 'CI');
INSERT INTO country (id, name, iso2) VALUES (55, 'Croatia', 'HR');
INSERT INTO country (id, name, iso2) VALUES (56, 'Cuba', 'CU');
INSERT INTO country (id, name, iso2) VALUES (57, 'Cyprus', 'CY');
INSERT INTO country (id, name, iso2) VALUES (58, 'Czech Republic', 'CZ');
INSERT INTO country (id, name, iso2) VALUES (59, 'Denmark', 'DK');
INSERT INTO country (id, name, iso2) VALUES (60, 'Djibouti', 'DJ');
INSERT INTO country (id, name, iso2) VALUES (61, 'Dominica', 'DM');
INSERT INTO country (id, name, iso2) VALUES (62, 'Dominican Republic', 'DO');
INSERT INTO country (id, name, iso2) VALUES (63, 'East Timor', 'TL');
INSERT INTO country (id, name, iso2) VALUES (64, 'Ecuador', 'EC');
INSERT INTO country (id, name, iso2) VALUES (65, 'Egypt', 'EG');
INSERT INTO country (id, name, iso2) VALUES (66, 'El Salvador', 'SV');
INSERT INTO country (id, name, iso2) VALUES (67, 'Equatorial Guinea', 'GQ');
INSERT INTO country (id, name, iso2) VALUES (68, 'Eritrea', 'ER');
INSERT INTO country (id, name, iso2) VALUES (69, 'Estonia', 'EE');
INSERT INTO country (id, name, iso2) VALUES (70, 'Ethiopia', 'ET');
INSERT INTO country (id, name, iso2) VALUES (71, 'Falkland Islands', 'FK');
INSERT INTO country (id, name, iso2) VALUES (72, 'Faroe Islands', 'FO');
INSERT INTO country (id, name, iso2) VALUES (73, 'Fiji Islands', 'FJ');
INSERT INTO country (id, name, iso2) VALUES (74, 'Finland', 'FI');
INSERT INTO country (id, name, iso2) VALUES (75, 'France', 'FR');
INSERT INTO country (id, name, iso2) VALUES (76, 'French Guiana', 'GF');
INSERT INTO country (id, name, iso2) VALUES (77, 'French Polynesia', 'PF');
INSERT INTO country (id, name, iso2) VALUES (78, 'French Southern Territories', 'TF');
INSERT INTO country (id, name, iso2) VALUES (79, 'Gabon', 'GA');
INSERT INTO country (id, name, iso2) VALUES (80, 'Gambia The', 'GM');
INSERT INTO country (id, name, iso2) VALUES (81, 'Georgia', 'GE');
INSERT INTO country (id, name, iso2) VALUES (82, 'Germany', 'DE');
INSERT INTO country (id, name, iso2) VALUES (83, 'Ghana', 'GH');
INSERT INTO country (id, name, iso2) VALUES (84, 'Gibraltar', 'GI');
INSERT INTO country (id, name, iso2) VALUES (85, 'Greece', 'GR');
INSERT INTO country (id, name, iso2) VALUES (86, 'Greenland', 'GL');
INSERT INTO country (id, name, iso2) VALUES (87, 'Grenada', 'GD');
INSERT INTO country (id, name, iso2) VALUES (88, 'Guadeloupe', 'GP');
INSERT INTO country (id, name, iso2) VALUES (89, 'Guam', 'GU');
INSERT INTO country (id, name, iso2) VALUES (90, 'Guatemala', 'GT');
INSERT INTO country (id, name, iso2) VALUES (91, 'Guernsey and Alderney', 'GG');
INSERT INTO country (id, name, iso2) VALUES (92, 'Guinea', 'GN');
INSERT INTO country (id, name, iso2) VALUES (93, 'Guinea-Bissau', 'GW');
INSERT INTO country (id, name, iso2) VALUES (94, 'Guyana', 'GY');
INSERT INTO country (id, name, iso2) VALUES (95, 'Haiti', 'HT');
INSERT INTO country (id, name, iso2) VALUES (96, 'Heard Island and McDonald Islands', 'HM');
INSERT INTO country (id, name, iso2) VALUES (97, 'Honduras', 'HN');
INSERT INTO country (id, name, iso2) VALUES (98, 'Hong Kong S.A.R.', 'HK');
INSERT INTO country (id, name, iso2) VALUES (99, 'Hungary', 'HU');
INSERT INTO country (id, name, iso2) VALUES (100, 'Iceland', 'IS');
INSERT INTO country (id, name, iso2) VALUES (101, 'India', 'IN');
INSERT INTO country (id, name, iso2) VALUES (102, 'Indonesia', 'ID');
INSERT INTO country (id, name, iso2) VALUES (103, 'Iran', 'IR');
INSERT INTO country (id, name, iso2) VALUES (104, 'Iraq', 'IQ');
INSERT INTO country (id, name, iso2) VALUES (105, 'Ireland', 'IE');
INSERT INTO country (id, name, iso2) VALUES (106, 'Israel', 'IL');
INSERT INTO country (id, name, iso2) VALUES (107, 'Italy', 'IT');
INSERT INTO country (id, name, iso2) VALUES (108, 'Jamaica', 'JM');
INSERT INTO country (id, name, iso2) VALUES (109, 'Japan', 'JP');
INSERT INTO country (id, name, iso2) VALUES (110, 'Jersey', 'JE');
INSERT INTO country (id, name, iso2) VALUES (111, 'Jordan', 'JO');
INSERT INTO country (id, name, iso2) VALUES (112, 'Kazakhstan', 'KZ');
INSERT INTO country (id, name, iso2) VALUES (113, 'Kenya', 'KE');
INSERT INTO country (id, name, iso2) VALUES (114, 'Kiribati', 'KI');
INSERT INTO country (id, name, iso2) VALUES (115, 'North Korea', 'KP');
INSERT INTO country (id, name, iso2) VALUES (116, 'South Korea', 'KR');
INSERT INTO country (id, name, iso2) VALUES (117, 'Kuwait', 'KW');
INSERT INTO country (id, name, iso2) VALUES (118, 'Kyrgyzstan', 'KG');
INSERT INTO country (id, name, iso2) VALUES (119, 'Laos', 'LA');
INSERT INTO country (id, name, iso2) VALUES (120, 'Latvia', 'LV');
INSERT INTO country (id, name, iso2) VALUES (121, 'Lebanon', 'LB');
INSERT INTO country (id, name, iso2) VALUES (122, 'Lesotho', 'LS');
INSERT INTO country (id, name, iso2) VALUES (123, 'Liberia', 'LR');
INSERT INTO country (id, name, iso2) VALUES (124, 'Libya', 'LY');
INSERT INTO country (id, name, iso2) VALUES (125, 'Liechtenstein', 'LI');
INSERT INTO country (id, name, iso2) VALUES (126, 'Lithuania', 'LT');
INSERT INTO country (id, name, iso2) VALUES (127, 'Luxembourg', 'LU');
INSERT INTO country (id, name, iso2) VALUES (128, 'Macau S.A.R.', 'MO');
INSERT INTO country (id, name, iso2) VALUES (129, 'North Macedonia', 'MK');
INSERT INTO country (id, name, iso2) VALUES (130, 'Madagascar', 'MG');
INSERT INTO country (id, name, iso2) VALUES (131, 'Malawi', 'MW');
INSERT INTO country (id, name, iso2) VALUES (132, 'Malaysia', 'MY');
INSERT INTO country (id, name, iso2) VALUES (133, 'Maldives', 'MV');
INSERT INTO country (id, name, iso2) VALUES (134, 'Mali', 'ML');
INSERT INTO country (id, name, iso2) VALUES (135, 'Malta', 'MT');
INSERT INTO country (id, name, iso2) VALUES (136, 'Man (Isle of)', 'IM');
INSERT INTO country (id, name, iso2) VALUES (137, 'Marshall Islands', 'MH');
INSERT INTO country (id, name, iso2) VALUES (138, 'Martinique', 'MQ');
INSERT INTO country (id, name, iso2) VALUES (139, 'Mauritania', 'MR');
INSERT INTO country (id, name, iso2) VALUES (140, 'Mauritius', 'MU');
INSERT INTO country (id, name, iso2) VALUES (141, 'Mayotte', 'YT');
INSERT INTO country (id, name, iso2) VALUES (142, 'Mexico', 'MX');
INSERT INTO country (id, name, iso2) VALUES (143, 'Micronesia', 'FM');
INSERT INTO country (id, name, iso2) VALUES (144, 'Moldova', 'MD');
INSERT INTO country (id, name, iso2) VALUES (145, 'Monaco', 'MC');
INSERT INTO country (id, name, iso2) VALUES (146, 'Mongolia', 'MN');
INSERT INTO country (id, name, iso2) VALUES (147, 'Montenegro', 'ME');
INSERT INTO country (id, name, iso2) VALUES (148, 'Montserrat', 'MS');
INSERT INTO country (id, name, iso2) VALUES (149, 'Morocco', 'MA');
INSERT INTO country (id, name, iso2) VALUES (150, 'Mozambique', 'MZ');
INSERT INTO country (id, name, iso2) VALUES (151, 'Myanmar', 'MM');
INSERT INTO country (id, name, iso2) VALUES (152, 'Namibia', 'NA');
INSERT INTO country (id, name, iso2) VALUES (153, 'Nauru', 'NR');
INSERT INTO country (id, name, iso2) VALUES (154, 'Nepal', 'NP');
INSERT INTO country (id, name, iso2) VALUES (155, 'Bonaire, Sint Eustatius and Saba', 'BQ');
INSERT INTO country (id, name, iso2) VALUES (156, 'Netherlands', 'NL');
INSERT INTO country (id, name, iso2) VALUES (157, 'New Caledonia', 'NC');
INSERT INTO country (id, name, iso2) VALUES (158, 'New Zealand', 'NZ');
INSERT INTO country (id, name, iso2) VALUES (159, 'Nicaragua', 'NI');
INSERT INTO country (id, name, iso2) VALUES (160, 'Niger', 'NE');
INSERT INTO country (id, name, iso2) VALUES (161, 'Nigeria', 'NG');
INSERT INTO country (id, name, iso2) VALUES (162, 'Niue', 'NU');
INSERT INTO country (id, name, iso2) VALUES (163, 'Norfolk Island', 'NF');
INSERT INTO country (id, name, iso2) VALUES (164, 'Northern Mariana Islands', 'MP');
INSERT INTO country (id, name, iso2) VALUES (165, 'Norway', 'NO');
INSERT INTO country (id, name, iso2) VALUES (166, 'Oman', 'OM');
INSERT INTO country (id, name, iso2) VALUES (167, 'Pakistan', 'PK');
INSERT INTO country (id, name, iso2) VALUES (168, 'Palau', 'PW');
INSERT INTO country (id, name, iso2) VALUES (169, 'Palestinian Territory Occupied', 'PS');
INSERT INTO country (id, name, iso2) VALUES (170, 'Panama', 'PA');
INSERT INTO country (id, name, iso2) VALUES (171, 'Papua new Guinea', 'PG');
INSERT INTO country (id, name, iso2) VALUES (172, 'Paraguay', 'PY');
INSERT INTO country (id, name, iso2) VALUES (173, 'Peru', 'PE');
INSERT INTO country (id, name, iso2) VALUES (174, 'Philippines', 'PH');
INSERT INTO country (id, name, iso2) VALUES (175, 'Pitcairn Island', 'PN');
INSERT INTO country (id, name, iso2) VALUES (176, 'Poland', 'PL');
INSERT INTO country (id, name, iso2) VALUES (177, 'Portugal', 'PT');
INSERT INTO country (id, name, iso2) VALUES (178, 'Puerto Rico', 'PR');
INSERT INTO country (id, name, iso2) VALUES (179, 'Qatar', 'QA');
INSERT INTO country (id, name, iso2) VALUES (180, 'Reunion', 'RE');
INSERT INTO country (id, name, iso2) VALUES (181, 'Romania', 'RO');
INSERT INTO country (id, name, iso2) VALUES (182, 'Russia', 'RU');
INSERT INTO country (id, name, iso2) VALUES (183, 'Rwanda', 'RW');
INSERT INTO country (id, name, iso2) VALUES (184, 'Saint Helena', 'SH');
INSERT INTO country (id, name, iso2) VALUES (185, 'Saint Kitts And Nevis', 'KN');
INSERT INTO country (id, name, iso2) VALUES (186, 'Saint Lucia', 'LC');
INSERT INTO country (id, name, iso2) VALUES (187, 'Saint Pierre and Miquelon', 'PM');
INSERT INTO country (id, name, iso2) VALUES (188, 'Saint Vincent And The Grenadines', 'VC');
INSERT INTO country (id, name, iso2) VALUES (189, 'Saint-Barthelemy', 'BL');
INSERT INTO country (id, name, iso2) VALUES (190, 'Saint-Martin (French part)', 'MF');
INSERT INTO country (id, name, iso2) VALUES (191, 'Samoa', 'WS');
INSERT INTO country (id, name, iso2) VALUES (192, 'San Marino', 'SM');
INSERT INTO country (id, name, iso2) VALUES (193, 'Sao Tome and Principe', 'ST');
INSERT INTO country (id, name, iso2) VALUES (194, 'Saudi Arabia', 'SA');
INSERT INTO country (id, name, iso2) VALUES (195, 'Senegal', 'SN');
INSERT INTO country (id, name, iso2) VALUES (196, 'Serbia', 'RS');
INSERT INTO country (id, name, iso2) VALUES (197, 'Seychelles', 'SC');
INSERT INTO country (id, name, iso2) VALUES (198, 'Sierra Leone', 'SL');
INSERT INTO country (id, name, iso2) VALUES (199, 'Singapore', 'SG');
INSERT INTO country (id, name, iso2) VALUES (200, 'Slovakia', 'SK');
INSERT INTO country (id, name, iso2) VALUES (201, 'Slovenia', 'SI');
INSERT INTO country (id, name, iso2) VALUES (202, 'Solomon Islands', 'SB');
INSERT INTO country (id, name, iso2) VALUES (203, 'Somalia', 'SO');
INSERT INTO country (id, name, iso2) VALUES (204, 'South Africa', 'ZA');
INSERT INTO country (id, name, iso2) VALUES (205, 'South Georgia', 'GS');
INSERT INTO country (id, name, iso2) VALUES (206, 'South Sudan', 'SS');
INSERT INTO country (id, name, iso2) VALUES (207, 'Spain', 'ES');
INSERT INTO country (id, name, iso2) VALUES (208, 'Sri Lanka', 'LK');
INSERT INTO country (id, name, iso2) VALUES (209, 'Sudan', 'SD');
INSERT INTO country (id, name, iso2) VALUES (210, 'Suriname', 'SR');
INSERT INTO country (id, name, iso2) VALUES (211, 'Svalbard And Jan Mayen Islands', 'SJ');
INSERT INTO country (id, name, iso2) VALUES (212, 'Swaziland', 'SZ');
INSERT INTO country (id, name, iso2) VALUES (213, 'Sweden', 'SE');
INSERT INTO country (id, name, iso2) VALUES (214, 'Switzerland', 'CH');
INSERT INTO country (id, name, iso2) VALUES (215, 'Syria', 'SY');
INSERT INTO country (id, name, iso2) VALUES (216, 'Taiwan', 'TW');
INSERT INTO country (id, name, iso2) VALUES (217, 'Tajikistan', 'TJ');
INSERT INTO country (id, name, iso2) VALUES (218, 'Tanzania', 'TZ');
INSERT INTO country (id, name, iso2) VALUES (219, 'Thailand', 'TH');
INSERT INTO country (id, name, iso2) VALUES (220, 'Togo', 'TG');
INSERT INTO country (id, name, iso2) VALUES (221, 'Tokelau', 'TK');
INSERT INTO country (id, name, iso2) VALUES (222, 'Tonga', 'TO');
INSERT INTO country (id, name, iso2) VALUES (223, 'Trinidad And Tobago', 'TT');
INSERT INTO country (id, name, iso2) VALUES (224, 'Tunisia', 'TN');
INSERT INTO country (id, name, iso2) VALUES (225, 'Turkey', 'TR');
INSERT INTO country (id, name, iso2) VALUES (226, 'Turkmenistan', 'TM');
INSERT INTO country (id, name, iso2) VALUES (227, 'Turks And Caicos Islands', 'TC');
INSERT INTO country (id, name, iso2) VALUES (228, 'Tuvalu', 'TV');
INSERT INTO country (id, name, iso2) VALUES (229, 'Uganda', 'UG');
INSERT INTO country (id, name, iso2) VALUES (230, 'Ukraine', 'UA');
INSERT INTO country (id, name, iso2) VALUES (231, 'United Arab Emirates', 'AE');
INSERT INTO country (id, name, iso2) VALUES (232, 'United Kingdom', 'GB');
INSERT INTO country (id, name, iso2) VALUES (233, 'United States', 'US');
INSERT INTO country (id, name, iso2) VALUES (234, 'United States Minor Outlying Islands', 'UM');
INSERT INTO country (id, name, iso2) VALUES (235, 'Uruguay', 'UY');
INSERT INTO country (id, name, iso2) VALUES (236, 'Uzbekistan', 'UZ');
INSERT INTO country (id, name, iso2) VALUES (237, 'Vanuatu', 'VU');
INSERT INTO country (id, name, iso2) VALUES (238, 'Vatican City State (Holy See)', 'VA');
INSERT INTO country (id, name, iso2) VALUES (239, 'Venezuela', 'VE');
INSERT INTO country (id, name, iso2) VALUES (240, 'Vietnam', 'VN');
INSERT INTO country (id, name, iso2) VALUES (241, 'Virgin Islands (British)', 'VG');
INSERT INTO country (id, name, iso2) VALUES (242, 'Virgin Islands (US)', 'VI');
INSERT INTO country (id, name, iso2) VALUES (243, 'Wallis And Futuna Islands', 'WF');
INSERT INTO country (id, name, iso2) VALUES (244, 'Western Sahara', 'EH');
INSERT INTO country (id, name, iso2) VALUES (245, 'Yemen', 'YE');
INSERT INTO country (id, name, iso2) VALUES (246, 'Zambia', 'ZM');
INSERT INTO country (id, name, iso2) VALUES (247, 'Zimbabwe', 'ZW');
INSERT INTO country (id, name, iso2) VALUES (248, 'Kosovo', 'XK');
INSERT INTO country (id, name, iso2) VALUES (249, 'Curaçao', 'CW');
INSERT INTO country (id, name, iso2) VALUES (250, 'Sint Maarten (Dutch part)', 'SX');
