INSERT INTO state (id, name, iso2, country_id) VALUES (1997, 'Rio de Janeiro', 'RJ', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (1998, 'Minas Gerais', 'MG', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (1999, 'Amapá', 'AP', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2000, 'Goiás', 'GO', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2001, 'Rio Grande do Sul', 'RS', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2002, 'Bahia', 'BA', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2003, 'Sergipe', 'SE', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2004, 'Amazonas', 'AM', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2005, 'Paraíba', 'PB', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2006, 'Pernambuco', 'PE', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2007, 'Alagoas', 'AL', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2008, 'Piauí', 'PI', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2009, 'Pará', 'PA', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2010, 'Mato Grosso do Sul', 'MS', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2011, 'Mato Grosso', 'MT', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2012, 'Acre', 'AC', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2013, 'Rondônia', 'RO', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2014, 'Santa Catarina', 'SC', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2015, 'Maranhão', 'MA', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2016, 'Ceará', 'CE', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2017, 'Distrito Federal', 'DF', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2018, 'Espírito Santo', 'ES', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2019, 'Rio Grande do Norte', 'RN', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2020, 'Tocantins', 'TO', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2021, 'São Paulo', 'SP', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (2022, 'Paraná', 'PR', 31);
INSERT INTO state (id, name, iso2, country_id) VALUES (4858, 'Roraima', 'RR', 31);
